startprojectapp/app/urls.py
from django.urls import path

from .views import authentication
from .views import questions

app_name = "app"

urlpatterns = [
    #: /login/
    path('login/', authentication.login, name="login"),
    #: /home/
    path('', authentication.index, name="index"),
    #: /app/
    path('questions', questions.list, name="list"),
    #ex: /app/1/
    path('<int:question_id>/', questions.details, name="details"),
    #: /app/1/results/
    path('<int:question_id>/results/', questions.results, name="results"),
    #: /app/1/votes
    path('<int:question_id>/votes/', questions.votes, name="votes"),
    #: /app/sample_error_500
    path('500', authentication.sample_error_500, name="500_error"),
]

startprojectapp/startprojectapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include("app.urls"))
]

handler404 = "startprojectapp.views.page_not_found_view"
handler500 = "startprojectapp.views.page_error_500_view"

startprojectapp/app/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date_published")

    def __str__(self):
        return self.question_text

    def was_published_recented(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

startprojectapp/app/views/authentication.py
from django.shortcuts import render

def login(request):
    return render(request, "app/authentication/login.html")

def index(request):
    return render(request, "app/index.html")

def sample_error_500(request):
    '''
    Method for test the 500 Error
    '''
    ope = 100/0

    return render(request, "app/index.html", {})

startprojectapp/app/views/questions.py
import datetime
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)


from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from ..models import Question, Choice
# Create your views here.

def list(request):
    logger.info('Index was accessed at ' + str(datetime.datetime.now()) + ' hours!')
    latest_question_list = Question.objects.filter(pub_date__lt=timezone.now()).order_by("pub_date")[:5]
    return render(request, "app/questions/list.html", {
        "latest_question_list": latest_question_list
    })


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "app/questions/details.html", {
        "question": question
    })


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "app/questions/results.html", {
        "question" : question
    })

def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        select_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "app/questions/details.html", {
            "question": question,
            "error_message": "Non hai scelto una risposta"
        })
    else:
        select_choice.votes = select_choice.votes + 1
        select_choice.save()
        return HttpResponseRedirect(reverse("app:results", args=(question_id,)))

startprojectapp/startprojectapp/views.py
import sys, traceback, cgi
from django.shortcuts import render

from django.http import HttpResponseServerError
from django.template import loader, Context, RequestContext

def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

def page_error_500_view(request, *args, **argv):

    t = loader.get_template('500.html')
    trace = traceback.format_exc()
    type, value, tb = sys.exc_info()

    filename = tb.tb_frame.f_code.co_filename
    name = tb.tb_frame.f_code.co_name
    line_no = tb.tb_lineno

    return render(request, '500.html', {
        'type': type.__name__,
        'trace': trace,
        'value': value
    })

startprojectapp/app/templates/app/authentication/login.html
{% extends 'master/layout/layout-login.html' %}
{% block contentarea %}
    <main class="form-signin w-100 m-auto">
      <form class="row g-3 needs-validation" novalidate>
        {% load static %}
        <img class="mb-1" src="{% static 'assets/images/login-icon.svg' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-1 fw-normal">Accedi</h1>

        <div class="form-floating">
          <input type="text" class="form-control" id="floatingInput" placeholder="Username" required>
          <label for="floatingInput" >Username</label>
          <div class="invalid-tooltip">
            Questo campo &egrave; obbligatorio
          </div>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" required>
          <label for="floatingPassword">Password</label>
          <div class="invalid-tooltip">
            Questo campo &egrave; obbligatorio
          </div>
        </div>

        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Resta collegato
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Accedi</button>
        <p class="mt-5 mb-3 text-muted">&copy; 3Ainformatica 2023</p>
      </form>
    </main>
  <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (() => {
      'use strict'

      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      const forms = document.querySelectorAll('.needs-validation')

      // Loop over them and prevent submission
      Array.from(forms).forEach(form => {
        form.addEventListener('submit', event => {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
        }, false)
      })
    })()
  </script>
{% endblock %}

startprojectapp/app/templates/app/index.html
{% extends 'master/layout/layout.html' %}
{% block contentarea %}
    INDEX
{% endblock %}

startprojectapp/app/templates/app/layout/footer.html
<footer><h1>FOOTER APPLICATION (Footer.html)</h1></footer>
</body>

startprojectapp/app/templates/app/layout/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>--django start project--</title>
</head>
<body>
    <h1>HEADER (Header.html)</h1>

startprojectapp/app/templates/app/layout/layout.html
{% load static %}
{% include "app/layout/header.html" %}
    <h1>BODY APPLICATION (Layout.html)</h1>
    <div>
        {% block contentarea %}
        {% endblock %}
    </div>
{% include "app/layout/footer.html" %}
</html>

startprojectapp/app/templates/app/questions/details.html
{% extends 'master/layout/layout.html' %}
{% block contentarea %}
    {% if question %}
        <form action="{% url 'app:votes' question.id %}" method="post">
        {%  csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}

                {% for choice in question.choice_set.all %}
                    <input type="radio"
                           name="choice"
                           id="choice{{ forloop.counter }}"
                           value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
        </form>
    {% endif %}
{% endblock %}

startprojectapp/app/templates/app/questions/list.html
{% extends 'master/layout/layout.html' %}
{% block contentarea %}
    <div class="row">
        <div class="col-md-2">
            {% if latest_question_list %}
                <center>
                    <ul class="list-group">
                    {% for question in latest_question_list  %}
                        <a href="{% url 'app:details' question.id %}">
                            <li class="list-group-item active" >
                                {{ question.question_text }}
                            </li>
                        </a>
                    {% endfor %}
                    </ul>
                </center>
            {% else %}
                  <p>Non ci sono domande disponibili</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

startprojectapp/app/templates/app/questions/results.html
{% extends 'master/layout/layout.html' %}
{% block contentarea %}
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'app:details' question.id %}">Voi votare ancora ?</a>
{% endblock %}

startprojectapp/app/templates/app/results.html
{% extends 'app/layout/layout.html' %}
{% block contentarea %}
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'app:details' question.id %}">Voi votare ancora ?</a>
{% endblock %}

startprojectapp/templates/master/layout/footer.html
<!-- Risolvere il problema del margine del footer -->
<br><br><br><br><br><br><br>
<footer class="footer mt-auto py-3 bg-light fixed-bottom">
    <div class="container">
        <p class="text-center text-muted">3Ainformatica - Tutti i diritti riservati &copy; 2023</p>
    </div>
  </footer>
</body>

startprojectapp/templates/master/layout/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>--django start project--</title>
    {% load static %}

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}

    {% load fontawesome_5 %}
    {% fontawesome_5_static %}

    <!-- Custom styles for this template -->
    <link href="{% static 'master/assets/css/sidebars.css'%}" rel="stylesheet">
</head>
<body>
    <header class="p-2 mb-3 border-bottom">
        <div class="container">
            <div class="row">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-auto text-dark text-decoration-none">
                    Ministero del Interno
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <!-- not delete -->
                </ul>

                <span>SERGIO ARELLANO</span>

                <div class="dropdown text-end ms-3">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        {% fa5_icon 'user-circle' %}
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li class="ms-3">
                            <p class="mb-1">PROFILE:</p>
                            <p>User Profile </p>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Logout</a></li>
                    </ul>
                </div>
              </div>
            </div>
            <div class="row">
                <div>
                    <img src="{% static 'assets/images/logo_navbar.png' %}" />
                </div>
            </div>
        </div>
    </header>

startprojectapp/templates/master/layout/layout-login.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Login</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'master/assets/css/signin.css'%}" rel="stylesheet">
  </head>
  <body class="text-center">
    {% block contentarea %}
    {% endblock %}
  </body>
</html>

startprojectapp/templates/master/layout/layout.html
{% load static %}
{% include "master/layout/header.html" %}
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                {% include "master/layout/slides.html" %}
            </div>
        <div class="col-md-10">
            {% block contentarea %}
            {% endblock %}
        </div>
        </div>
    </div>
{% include "master/layout/footer.html" %}
</html>

startprojectapp/templates/master/layout/slides.html
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px;">
        <ul class="list-unstyled ps-0">
          <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
              Home
            </button>
            <div class="collapse show" id="home-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Overview</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Updates</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Reports</a></li>
              </ul>
            </div>
          </li>
          <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
              Dashboard
            </button>
            <div class="collapse" id="dashboard-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Overview</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Weekly</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Monthly</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Annually</a></li>
              </ul>
            </div>
          </li>
          <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
              Orders
            </button>
            <div class="collapse" id="orders-collapse">
              <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">New</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Processed</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Shipped</a></li>
                <li><a href="#" class="link-dark d-inline-flex text-decoration-none rounded">Returned</a></li>
              </ul>
            </div>
          </li>
        </ul>
  </div>